
spring:

  security:
    user:
      name: admin
      password: 1234

  datasource:
    url: jdbc:postgresql://localhost:5432/elearning
    username: postgres
    password: admin
    
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
    
  flyway:
    enabled: true
    driver-class-name: org.postgresql.Driver
